### ISSUE TITLE
 Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php on line 20

### ISSUE THREAD

**Issue by sakinaaf** [zendframework/zend-mail#233] opened 2019-08-01 17:21 UTC
Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php on line 20

**Comment by froschdesign** [comment] 2019-08-01 19:06
For the SMTP functionality you must install the zend-servicemanager. The service manager is not strictly required for zend-mail and _basic_ mail creation and sending. Therefore it is listed as [suggested package](https://getcomposer.org/doc/04-schema.md#suggest).

Install:

```bash
$ composer require zendframework/zend-servicemanager
```
The note is also given by Composer after installing zend-mail.

https://github.com/zendframework/zend-mail/blob/ece418b37aaf8a98c991d7f0c198408043a2172d/composer.json#L34-L37

---

Duplicate of #62

**Closed by froschdesign** 2019-08-01 19:06 UTC

**Comment by glensc** [comment] 2019-08-01 21:18
well. the code could give appropriate exception:

```php
throw new \RuntimeException("This functionality requires Zend ServiceManager, to install invoke: composer require zendframework/zend-servicemanager");
```

this is how Symfony does it. uncaught exception leads to believe there's a bug.

**Comment by froschdesign** [comment] 2019-08-01 21:29
@glensc 
This kind of exception can also help in other components!
It would be great, if can add this idea to the [maintainers repository](https://github.com/zendframework/maintainers/issues) as a new issue report.

**Comment by boesing** [comment] 2019-08-02 06:53
@froschdesign 
I would prefer having satellite packages with the next major version of those packages instead of having an exception like this.
Satellite packages would also ensure proper version requirements as just the pure existence of the package probably wont make this work.
Sure, one could add a `conflict` aswell but I still like satellite packages over exceptions.

But for existing packages like this, an exception would be ofc a suitable solution

**Comment by froschdesign** [comment] 2019-08-02 07:19
@boesing 
Please add your ideas and suggestions to the [maintainers repository](https://github.com/zendframework/maintainers/issues) because this issue is closed and any further comments will be forgotten.
